### ISSUE TITLE
Cannot handle multiple occurrences 

### ISSUE THREAD

**Issue by tiborsimon** [posva/markdown-it-custom-block#1]
The lib cannot handle multiple occurrences of the same __custom block__. 

# Error case 1

Using the same __custom block__ twice without separation. The lib cannot transform the blocks at all.

### Used custom block
```
const md = markdownit().use(customBlock, {
  example (arg) {
    return `<example-${arg}/>`
  }
})
```

### Test fixture
```
---
desc: Element
---

Two occurrences no separation
.
@[example](button1)
@[example](button2)
.
<example-button1/>
<example-button2/>
.
```

### Output
```
  Custom Blocks
    Element
      1) Two occurrences no separation


  0 passing (42ms)
  1 failing

  1) Custom Blocks Element Two occurrences no separation:

      AssertionError: expected '<p>@<a href="button1">example</a>\n@<a href="button2">example</a></p>\n' to equal '<example-button1/>\n<example-button2/>\n'
      + expected - actual

      -<p>@<a href="button1">example</a>
      -@<a href="button2">example</a></p>
      +<example-button1/>
      +<example-button2/>

      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:169:32)
      at Context.<anonymous> (node_modules/markdown-it-testgen/index.js:188:26)
```

# Error case 2

Using the same __custom block__ twice with an empty line between them. The first transform will be repeated twice.

### Used custom block
```
const md = markdownit().use(customBlock, {
  example (arg) {
    return `<example-${arg}/>`
  }
})
```

### Test fixture
```
---
desc: Element
---

Two occurrences with separation
.
@[example](button1)

@[example](button2)
.
<example-button1/>
<example-button2/>
.
```

### Output
```
   Custom Blocks
    Element
      1) Two occurrences with separation


  0 passing (38ms)
  1 failing

  1) Custom Blocks Element Two occurrences with separation:

      AssertionError: expected '<example-button1/>\n<example-button1/>\n' to equal '<example-button1/>\n<example-button2/>\n'
      + expected - actual

       <example-button1/>
      -<example-button1/>
      +<example-button2/>

      at Function.assert.strictEqual (node_modules/chai/lib/chai/interface/assert.js:169:32)
      at Context.<anonymous> (node_modules/markdown-it-testgen/index.js:188:26)
```

**Comment by posva** [comment]
I had a hard time creating the tokenizer because I couldn't find any doc for it, so I inspired myself from https://github.com/rotorz/markdown-it-block-embed/
If you manage to find I fix, I'll gladly take a PR 🙂

**Comment by posva** [comment]
On a second thought, the two occurrences without separation is not necessary, but the other one really bothers me so I'm going to take a look

**Comment by posva** [comment]
Ok, got it fixed, it was easier than I thought 🙂

**Comment by tiborsimon** [comment]
Okay. Probably I will have some time in the evening to take a look at this too. 

Btw.. I was trying to achieve a wrapped figure block with the plugin:

```
@[figures](start)
@[figure](url1)
@[figure](url2)
@[figures](end)
```

That should expand to

```
<div class="figures">
  <img src="url1" />
  <img src="url2" />
</div>
```

It would be nice to be able to use the block transformations without separations :)

**Comment by posva** [comment]
I'll give it a try for the block without separations but I'll be open for contributions on that one since I don't really need it and it will work using blank lines between them 😄 (a bit ugly but admissible imo)

**Comment by posva** [comment]
Btw, for your case, you should maybe directly use HTML 🙂

**Comment by posva** [comment]
I'll close this and open a new shorter issue in case anyone wants to contribute

**Comment by tiborsimon** [comment]
Yep, I used to use raw HTML. The previous example was a simplified one. The real use case is the following:

```
@[figures](start)
@[figure](1#My caption 1#401#url1)
@[figure](2#My caption 2#402#url2)
@[figures](end)
```
```
<div class="figures">
<figure>
  <img src="url1" width="401" alt="My caption 1">
  <figcaption>Fig 1: My caption 1</figcaption>
</figure>
<figure>
  <img src="url2" width="402" alt="My caption 2">
  <figcaption>Fig 2: My caption 2</figcaption>
</figure>
</div>
```

I hate to type in anything _twice_, so I prefer the  __custom block__ way. Actually I was very happy that I find your module :relaxed: .

**Comment by posva** [comment]
Cool, it makes it easier indeed 🙂. if you manage in adding the no blank line feature, make sure to send a PR. I already added your test case 😉
