### ISSUE TITLE
Multiple template literals

### ISSUE THREAD

**Issue by wtty** [posva/markdown-it-custom-block#4]
Is it possible to use more than one template literal?

```javascript
const customBlock = require('markdown-it-custom-block')

markdownit()
  .use(customBlock, {
    test (one, two) {
      return `<div class="one">${one}</div><div class="two">${two}</div>`
    }
  })
```
```markdown
@[test](One),(Two)
```

**Comment by posva** [comment]
Yes, you can but you can only pass one argument with the markdown syntax: `@[test](One,Two)`
You'll have to split in the function later.

A safer and more flexible way is to pass json: `@[test](['One', 'Two'])` and parse it inside of the handler:

```js
markdownit()
  .use(customBlock, {
    test (json) {
     const [one, two] = JSON.parse(json)
      return `<div class="one">${one}</div><div class="two">${two}</div>`
    }
  })
```

**Comment by AGDholo** [comment]
VuePress JSON.parse error:  
SyntaxError: Unexpected token ' in JSON at position 1  
```
module.exports = {
  markdown: {
    config: md => {
      md.use(require('markdown-it-custom-block'), {
        test (json) {
          const [one, two] = JSON.parse(json)
          return `<div class="one">${one}</div><div class="two">${two}</div>`
        }
      })
    }
  }
}
```
``` @[test](['One', 'Two']) ```

I try to use Array,but can't parse correctly.

**Comment by SpoinkyNL** [comment]
In case someone is trying to figure this one out, use double quotes

```
@[test](["One", "Two"])
```
